### ISSUE TITLE
Build error: No named parameter 

### ISSUE THREAD

**Issue by Tomekske** [buraktabn/categorized_dropdown#1]
Hey,

I tried installing your widget because it has everything I look for in a dropdown widget. But importing the library I encountered three error messages.

/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/categorized_dropdown-1.0.0/lib/src/categorized_dropdown.dart(313,11): error GBF4691A2: No named parameter with the name 'enabled'.

AppData/Local/Pub/Cache/hosted/pub.dartlang.org/categorized_dropdown-1.0.0/lib/src/categorized_dropdown.dart(325,15): error GBF4691A2: No named parameter with the name 'enabled'.

AppData/Local/Pub/Cache/hosted/pub.dartlang.org/categorized_dropdown-1.0.0/lib/src/categorized_dropdown.dart(361,7): error GBF4691A2: No named parameter with the name 'enableFeedback'

**Comment by buraktabn** [comment]
I had to make category names disabled. Since Flutter merged this recently in here flutter/flutter#76968, I recommend using master channel for now.
